# Generated by Django 5.0.4 on 2024-08-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreview',
            name='stars',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='carreview',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carreview',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='carreview',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
