# Generated by Django 5.0.4 on 2024-08-15 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carreview_stars_alter_carreview_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreview',
            name='stars',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
